#!/usr/bin/env bash

set -euf -o pipefail

hash git 2>/dev/null || { echo >&2 "I require git but it's not installed.  Aborting."; exit 1; }

mkdir -p projects

cd projects

names=(
  "app.exploreapollo.org"
  "exploreapollo-api"
)

for name in ${names[@]}; do
  if [ ! -d "$name" ]; then
    git clone git@github.com:UTD-CRSS/$name.git
  fi
done

echo "up and running."
